apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkin_try
spec: 
  replicas: 3
  selector: 
    matchLabels:
      type: app1
  template:
    metadata:
      name: pod1
      labels:
        type: app1
    spec:
      containers:
        - name: jaycontainer
          image: jaysawant123/image1
          ports:
            - containerPort: 80